import type { ClassificationRule } from '../types';

export const DEFAULT_RULES: ClassificationRule[] = [
   // ── Description rules ────────────────────────────────────────────────────
   {
      id: 'default-d-1',
      keyword: 'virement permanent',
      category: 'Logement',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-2',
      keyword: 'loyer',
      category: 'Logement',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-3',
      keyword: 'edf',
      category: 'Electricité',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-4',
      keyword: 'electricité',
      category: 'Electricité',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-5',
      keyword: 'engie',
      category: 'Electricité',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-6',
      keyword: 'orange',
      category: 'Internet',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-7',
      keyword: 'free',
      category: 'Internet',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-8',
      keyword: 'sfr',
      category: 'Internet',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-9',
      keyword: 'bouygues',
      category: 'Internet',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-10',
      keyword: 'fibre',
      category: 'Internet',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-11',
      keyword: 'sncf',
      category: 'Transport',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-12',
      keyword: 'ratp',
      category: 'Transport',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-13',
      keyword: 'navigo',
      category: 'Transport',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-14',
      keyword: 'uber',
      category: 'Transport',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-15',
      keyword: 'carrefour',
      category: 'Supermarché',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-16',
      keyword: 'monoprix',
      category: 'Supermarché',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-17',
      keyword: 'lidl',
      category: 'Supermarché',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-18',
      keyword: 'aldi',
      category: 'Supermarché',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-19',
      keyword: 'leclerc',
      category: 'Supermarché',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-20',
      keyword: 'franprix',
      category: 'Supermarché',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-21',
      keyword: 'restaurant',
      category: 'Restaurant',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-22',
      keyword: 'brasserie',
      category: 'Restaurant',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-23',
      keyword: 'café',
      category: 'Restaurant',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-24',
      keyword: 'mcdonald',
      category: 'Restaurant',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-25',
      keyword: 'burger',
      category: 'Restaurant',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-26',
      keyword: 'pharmacie',
      category: 'Santé',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-27',
      keyword: 'docteur',
      category: 'Santé',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-28',
      keyword: 'médecin',
      category: 'Santé',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-29',
      keyword: 'clinique',
      category: 'Santé',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-30',
      keyword: 'salaire',
      category: 'Revenu',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-31',
      keyword: 'virement reçu',
      category: 'Revenu',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-32',
      keyword: 'retrait distributeur',
      category: 'Retrait',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-33',
      keyword: 'retrait dab',
      category: 'Retrait',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-34',
      keyword: 'amazon',
      category: 'Achat',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-35',
      keyword: 'fnac',
      category: 'Achat',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-36',
      keyword: 'darty',
      category: 'Achat',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-37',
      keyword: 'impôt',
      category: 'Impôt',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-38',
      keyword: 'trésor public',
      category: 'Impôt',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-39',
      keyword: 'dgfip',
      category: 'Impôt',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-40',
      keyword: 'assurance',
      category: 'Administratif',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-41',
      keyword: 'intercompte',
      category: 'Intercompte',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-42',
      keyword: 'virement vers',
      category: 'Intercompte',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-43',
      keyword: 'sport',
      category: 'Sport',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-44',
      keyword: 'fitness',
      category: 'Sport',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-45',
      keyword: 'salle de sport',
      category: 'Sport',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-46',
      keyword: 'vétérinaire',
      category: 'Chien',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-47',
      keyword: 'royal canin',
      category: 'Chien',
      isDefault: true,
      matchField: 'description',
   },
   {
      id: 'default-d-48',
      keyword: 'animalis',
      category: 'Chien',
      isDefault: true,
      matchField: 'description',
   },

   // ── Bank category rules ───────────────────────────────────────────────────
   // Boursobank
   {
      id: 'default-b-1',
      keyword: 'restaurants, bars, discothèques…',
      category: 'Restaurant',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-2',
      keyword: 'divertissement - culture (ciné, théâtre, concerts…)',
      category: 'Loisir Voyage',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-3',
      keyword: 'courses alimentaires',
      category: 'Supermarché',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-4',
      keyword: 'transports en commun',
      category: 'Transport',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-5',
      keyword: 'santé',
      category: 'Santé',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-6',
      keyword: 'logement',
      category: 'Logement',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-7',
      keyword: 'éducation',
      category: 'Education',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-8',
      keyword: 'sport',
      category: 'Sport',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-9',
      keyword: 'abonnements et téléphonie',
      category: 'Mobile',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-10',
      keyword: 'revenus',
      category: 'Revenu',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-11',
      keyword: 'épargne et placements',
      category: 'Rendement',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-12',
      keyword: 'impôts et taxes',
      category: 'Impôt',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-13',
      keyword: 'animaux',
      category: 'Chien',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-14',
      keyword: 'achats et shopping',
      category: 'Achat',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-15',
      keyword: 'retraits',
      category: 'Retrait',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-16',
      keyword: 'virements internes',
      category: 'Intercompte',
      isDefault: true,
      matchField: 'bankCategory',
   },
   // Hello Bank
   {
      id: 'default-b-17',
      keyword: 'loyer',
      category: 'Logement',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-18',
      keyword: 'internet, tv',
      category: 'Internet',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-19',
      keyword: "retrait d'espèces",
      category: 'Retrait',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-20',
      keyword: 'virement émis',
      category: 'Intercompte',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-21',
      keyword: 'salaire',
      category: 'Revenu',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-22',
      keyword: 'remboursement',
      category: 'Santé',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-23',
      keyword: 'assurance',
      category: 'Administratif',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-24',
      keyword: 'abonnement',
      category: 'Mobile',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-25',
      keyword: 'supermarché',
      category: 'Supermarché',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-26',
      keyword: 'restaurant',
      category: 'Restaurant',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-27',
      keyword: 'transport',
      category: 'Transport',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-28',
      keyword: 'éducation / formation',
      category: 'Education',
      isDefault: true,
      matchField: 'bankCategory',
   },
   {
      id: 'default-b-29',
      keyword: 'impôts',
      category: 'Impôt',
      isDefault: true,
      matchField: 'bankCategory',
   },
];
